### ISSUE TITLE
Distinguish different buildings

### ISSUE THREAD

**Issue by trubitsyn** [trubitsyn/bmstu-schedule-diff#1]
Currently it thinks all lessons take place at the same building.

**Comment by gabolaev** [comment]
hm, maybe you can check the 'л' letter existence at the end of auditorium code

**Comment by gabolaev** [comment]
but, anyway, that is not an ideal resolution, because there are many other buildings and i don't really know,  how to distinguish them

**Comment by trubitsyn** [comment]
See https://github.com/trubitsyn/bmstu-schedule-diff/commit/e7c756484cfa44f96e3f58fed10d597f28d83473
